org.gradle.jvmargs=-Xmx6000M -Dkotlin.daemon.jvm.options=-Xmx2048M
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
kotlin.incremental=true
kotlin.code.style=official
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=false
org.gradle.configuration-cache=false

